name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AvishkaGihan
          svg_out_path: github-contribution-grid-snake-dark.svg
          snake_color: 'blue'
          color_snake: "blue"
          color_dots: "#2D333B", "#006D32", "#26A641", "#39D353"

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          message: 'Generate Snake Animation'
          add: 'github-contribution-grid-snake-dark.svg'
